### ISSUE TITLE
veil migt be worth a look

### ISSUE THREAD

**Issue by necrose99** [postrequest/link#1]
veil evasion

https://github.com/topics/antivirus-evasion 

https://github.com/PushpenderIndia/crypter 

https://github.com/KooroshRZ/Evader cpp 

https://github.com/NishanthSpShetty/crust transpiler cpp > rust...

**Comment by postrequest** [comment]
Hey necrose99, thank you for the feedback!

Ideally the initial execution is not the link payload and instead another payload that will then execute link.
For example something like [this](https://github.com/postrequest/xeca) (if you wanted a PowerShell payload).

There are plans for introducing this type of static-analysis evasion, but for now there is other functionality that will be addressed.
