### ISSUE TITLE
Could not find DLL

### ISSUE THREAD

**Issue by wiwei132** [postrequest/link#10]
hi postrequest:
        when i install it on my ubuntu 18.04 use default kali-install.sh
        report """"Could not find DLL...."""" 
        this error report sooo simple!  

hava a nice day !

**Comment by postrequest** [comment]
Only support for Kali will be addressed, that script is for Kali only. 
It has been tested and works on other distributions and operating systems, but they will not be supported.

If Ubuntu is required, the correct dependencies must be installed. Usually it just a difference in the name of the package.

Best of luck!
