### ISSUE TITLE
Could not find tool, even after running sharp init and re-installing link.

### ISSUE THREAD

**Issue by grag1337** [postrequest/link#11]
Interacting with the links works fine, but when I go to run something like `sharp init svchost winPEAS` it dumps `could not find tool, at the main menu the following command may help: sharp init`. Whenever I run that command it just prints `updating sharpcollection` and nothing changes. Am I doing something wrong?

**Comment by postrequest** [comment]
Hi @grag1337,

Thanks for trying out link. `sharp init` is for downloading SharpCollection.

When interacting with a link, the command `sharp` provides example usage:
```
sharp <process> <tool> <parameters>
eg: sharp svchost SharpKatz --Command logonpasswords
```

Unfortunately the winPEAS executable seems to have issues executing on the target. It raises the the exception 0xC0000409 (STATUS_FAIL_FAST_EXCEPTION). Other .NET executables work as intended, so not attributing this error to link.

**Comment by grag1337** [comment]
Just as clarification, that was just an example of what was being ran. It didn't matter which sharp module I ran, the same message would be printed. Afaik it's not winpeas that was the cause.
