### ISSUE TITLE
generate-osx issue

### ISSUE THREAD

**Issue by starryloki** [postrequest/link#12]
🔗 > generate-osx xxx:xxx
first osx link build will take time
building osx cross compilation dependencies
osxcross cloned
OSX 10.11 SDK downloaded
updated clang build
building osxcross... this will take a while
osxcross built
please wait...
No such file or directory (os error 2)
No such file or directory (os error 2)
------------------------------------------------------
I have this issue on macOS, Kali, CentOS

**Comment by starryloki** [comment]
btw, how to reset the status of build? After I remove link and reclone, It's not first build anymore

**Comment by postrequest** [comment]
Hi @starryloki,

Currently only support kali. Did you run the install script?

**Comment by starryloki** [comment]
> Hi @starryloki,
> 
> Currently only support kali. Did you run the install script?

yes, I did everything you wrote and I wonder how to reset build status?

**Comment by postrequest** [comment]
To start the build of osxcross again, delete the `~/.link/3rdparty/osxcross` directory.
To start the build of your osx link again, delete the `~/.link/links/osx` directory.

If you have ran the `kali-install.sh` script and it is not working, please delete the `~/.link` directory and rerun the script. Just checking, but please ensure kali is updated. Please post the output of both the install script and link generation.

**Comment by starryloki** [comment]
fixed! thx
