### ISSUE TITLE
rustup does not have x86_64-pc-windows-gnu target

### ISSUE THREAD

**Issue by ctfpwner** [postrequest/link#4]
Hi, when I try to generate a windows link I get:

```
> generate 10.10.10.10:8443
rustup does not have x86_64-pc-windows-gnu target, the following command may help:
rustup target add x86_64-pc-windows-gnu
```

However, I do. Here's my cargo config. Any tip?

```
$ cat .cargo/config 
[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/x86_64-w64-mingw32/bin/ar"
```

Thank you.

**Comment by postrequest** [comment]
Hi ctfpwner,

The cargo config specifies the location of the necessary tools to compile the required target, not the toolchain.

The Windows link relies on the standard library and therefore rust requires the _**x86_64-pc-windows-gnu**_ standard library to compile. The generate command provided the answer you were looking for `rustup target add x86_64-pc-windows-gnu`.

For more information, please check [here](https://rust-lang.github.io/rustup/cross-compilation.html) or alternatively use the [install](https://github.com/postrequest/link/blob/main/kali-install.sh) script.

**Comment by ctfpwner** [comment]
Yes, and I did exactly that as well.

```
$ rustup target add x86_64-pc-windows-gnu
info: component 'rust-std' for target 'x86_64-pc-windows-gnu' is up to date
```

Same issue, I ran the kali install script, and run the command above again. Any help troubleshooting?

**Comment by ctfpwner** [comment]
I'm pretty sure cross compilation for Windows is broke because of the openssl package. Even though the `generate` command seems to doesn't even try to build. You can certainly reproduce it with a fresh Kali install, the command below fails.

```
cargo build --target=x86_64-pc-windows-gnu
```

**Comment by ctfpwner** [comment]
Nevermind, figured it out. Problem was on my side. Thank you.
