### ISSUE TITLE
cargo not installed, the following command may help:

### ISSUE THREAD

**Issue by jiexiaobai** [postrequest/link#7]
cargo not installed, the following command may help:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

**Hello, my local virtual machine can run this project, but VPS is suitable for Kali and cannot run. After running, it will be displayed as above**

**Comment by slimwang** [comment]
Is cargo in your shell path?
```
echo $PATH | grep cargo
```
If not, manually add `/home/yourusername/.cargo/bin/` to your shell's $PATH.

**Comment by qianxiaotest** [comment]
是添加到 link.d中吗

**Comment by postrequest** [comment]
Hi @jiexiaobai,

Your answer is in your question, please install rust (which includes cargo).

Also know that if you plan on using link on another distribution or operating system you will be required to install the comparable dependencies from the [install script](https://github.com/postrequest/link/blob/main/kali-install.sh).

**Comment by slimwang** [comment]
> 是添加到 link.d中吗

如果是kali的话，就把`export PATH=/home/yourusername/.cargo/bin:$PATH`加在`~/.zshrc`里
记得把yourusername改成你的用户名
