### ISSUE TITLE
What is the reason for this error?

### ISSUE THREAD

**Issue by Air-m1** [postrequest/link#8]
`root@CzTeam:~/LinkAkihi/link-main# ./target/release/link

                                    .-') _       .-. .-')
                                   ( OO ) )      \  ( OO )
 ,--.             ,-.-')       ,--./ ,--,'       ,--. ,--.
 |  |.-')         |  |OO)      |   \ |  |\       |  .'   /
 |  | OO )        |  |  \      |    \|  | )      |      /,
 |  |`-' |        |  |(_/      |  .     |/       |     ' _)
(|  '---.'       ,|  |_.'      |  |\    |        |  .   \
 |      |       (_|  |         |  | \   |        |  |\   \
 `------'         `--'         `--'  `--'        `--' '--'
Start web server (Y/n)? y
starting server
Please provide bind address (eg: 0.0.0.0:443): 【Cloud server public network IP】:19991
Could not bind to 【Cloud server public network IP】:19991: Cannot assign requested address (os error 99)
`
What is the reason for this error?

**Comment by postrequest** [comment]
This is not a link issue, you may have typed in your IP address incorrectly. 

If you are having troubles, assigning to 0.0.0.0 should always work.
